name: Staging Build

on:
  push:
    branches:
      - next

env:
  GITHUB_REGISTRY: ghcr.io
  IMAGE_NAME: coollabsio/coolify-docs
  VITE_ANALYTICS_DOMAIN: next.coolify.io/docs
  VITE_SITE_URL: https://next.coolify.io/docs/

jobs:
  build-push:
    strategy:
      matrix:
        include:
          - arch: amd64
            platform: linux/amd64
            runner: ubuntu-24.04
          - arch: aarch64
            platform: linux/arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ${{ env.GITHUB_REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image (${{ matrix.arch }})
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: ${{ matrix.platform }}
          build-args: |
            VITE_ANALYTICS_DOMAIN=${{ env.VITE_ANALYTICS_DOMAIN }}
            VITE_SITE_URL=${{ env.VITE_SITE_URL }}
            VITE_KORREKTLY_API_TOKEN=${{ secrets.VITE_KORREKTLY_API_TOKEN }}
            VITE_KORREKTLY_BASE_URL=${{ secrets.VITE_KORREKTLY_BASE_URL }}
            VITE_KORREKTLY_DATASET_ID=${{ secrets.VITE_KORREKTLY_DATASET_ID }}
          push: true
          tags: |
            ${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_NAME }}:next-${{ matrix.arch }}
          cache-from: type=gha,scope=build-${{ matrix.arch }}
          cache-to: type=gha,mode=max,scope=build-${{ matrix.arch }}

  merge-manifest:
    runs-on: ubuntu-24.04
    needs: build-push
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Login to ${{ env.GITHUB_REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create & publish manifest on ${{ env.GITHUB_REGISTRY }}
        run: |
          docker buildx imagetools create \
          ${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_NAME }}:next-amd64 \
          ${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_NAME }}:next-aarch64 \
          --tag ${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_NAME }}:next

      - name: Deploy to Coolify
        run: |
          curl --request GET '${{ secrets.COOLIFY_WEBHOOK_NEXT }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
